In [4]:
import numpy as np

x1, x2, x3, y = np.loadtxt("cracker_barrel.txt", skiprows=1, unpack=True)

X = np.column_stack((np.ones(x1.size), x1, x2, x3))

Y = y.reshape(-1, 1)

In [5]:
y

array([52., 17., 46., 70., 43., 60., 23., 43., 28., 31., 65., 15., 15.,
       59., 52., 22., 68., 34., 30., 56., 50., 36., 68., 25., 38., 30.,
       56., 19., 19., 41.])

In [6]:
Y

array([[52.],
       [17.],
       [46.],
       [70.],
       [43.],
       [60.],
       [23.],
       [43.],
       [28.],
       [31.],
       [65.],
       [15.],
       [15.],
       [59.],
       [52.],
       [22.],
       [68.],
       [34.],
       [30.],
       [56.],
       [50.],
       [36.],
       [68.],
       [25.],
       [38.],
       [30.],
       [56.],
       [19.],
       [19.],
       [41.]])

In [7]:
def predict(X, w):
    return np.matmul(X, w);

In [8]:
fake_weights = np.array([[0.1],
                  [0.2],
                  [0.3],
                  [0.4]])

In [9]:
predict(X, fake_weights)

array([[16.2],
       [ 7.7],
       [13.7],
       [15.8],
       [12.8],
       [21.6],
       [11.2],
       [ 9.3],
       [12.9],
       [ 9.9],
       [13.2],
       [ 7.4],
       [ 5.9],
       [12.9],
       [10.6],
       [ 9.6],
       [12.1],
       [12.3],
       [10.5],
       [14.8],
       [13.4],
       [11.3],
       [12.1],
       [ 8.4],
       [ 9.5],
       [ 9.9],
       [11.6],
       [ 8.3],
       [ 7.9],
       [11.2]])

In [ ]:
def loss(X, Y, w):
    predictions = predict(X, w)
    return np.average((predictions - Y) ** 2)

In [ ]:
loss(X, Y, fake_weights)

In [ ]:
def gradient(X, Y, w):
    return 2 * np.matmul(X.T, (predict(X, w) - Y)) / X.shape[0]

In [ ]:
gradient(X, Y, fake_weights)

In [ ]:
def train(X, Y, iterations, lr):
    w = np.zeros((X.shape[1], 1))

    for i in range(iterations):
        print("Iteration %4d => Loss: %.20f" % (i, loss(X, Y, w)))
        w -= gradient(X, Y, w) * lr
    return w

In [ ]:
w = train(X, Y, iterations=100000, lr=0.001)

In [ ]:
w

In [ ]:
predict(X[0], w)

In [ ]:
Y[0]